version: "3.9"
services:
  snippetstorepai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5060:4000"
    environment:
      - MONGODB_URI=mongodb://snippetstoredb:27017
      - MONGODB_USER=dbadmin
      - MONBODB_PWD=dbpwd
    networks:
      - globalnetwork
  mongo:
    container_name: "snippetstoredb"
    image: mongo:6.0.2
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbadmin
      - MONGO_INITDB_ROOT_PASSWORD=dbpwd
    volumes:
      - snippetdata:/data/db
    networks:
      - globalnetwork
networks:
  globalnetwork:
    name: globalnetwork
volumes:
  snippetdata: